### ISSUE TITLE
doubleOnPad not working properly

### ISSUE THREAD

**Issue by umxprime** [PrimaryFeather/Sparrow-Framework#1069]
doubleOnPad does not work properly on our universal app with 1.3
In SPTexture on line 266,
glTexture.scale = [path contentScaleFactor];
seems to cause the issue, because when I comment it, things works flawlessly on iPad, but it breaks the iPhone retina scale.

Something like this did the trick for me :

if (!(IS_DEVICE_IPAD() && [SPStage doubleResolutionsOnPad])) {
    glTexture.scale = [path contentScaleFactor];
}

**Comment by PrimaryFeather** [comment]
Hm, are you sure? The "doubleOnPad" feature was introduced in Sparrow 1.3, so I tested it rather extensively. Have you had a look at this tutorial?

http://wiki.sparrow-framework.org/manual/universal_app_development

It shows you how exactly this feature is supposed to be used.

Daniel

**Comment by umxprime** [comment]
Well I understood the idea to scale down the iPad stage size values, but my project started with 1.2, with 1024x768 for iPad, and I did my own SPTexture category to let it use @2x texture for iPad without down sizing it to 512x384.
Our UI use sometime @2x textures, sometimes iPad/iPhone specific assets.
I think we will try out down sizing on our next project if it is needed for doubleOnPad to work properly.
I though doubleOnPad let us load @2x/@4x on iPad with default screen bounds size.

**Comment by PrimaryFeather** [comment]
Ah, OK, I see what you mean! Yes, the way this is working was changed in that Sparrow version, that's why you are having difficulties. In your case, I guess you shouldn't use "doubleOnPad" then, because that expects that you use only half (iPad 1+2) or quarter (iPad 3) of the resolution for the stage size.

I'll close the issue then! Except you need anything else, then you can of course re-open it any time.
